Add Web Management Interface using AWS Amplify Gen2
aws-samples/ros2-ota-firmware-updates pull request #1
Opened 2024-12-16 08:45 UTC by Folotu

This PR introduces a web-based management interface for the ROS2 OTA firmware updates system using AWS Amplify. The web application provides a user-friendly way to monitor and manage firmware updates across your fleet of ROS2 devices.

Key Features:

- Secure authentication using Amazon Cognito
- Real-time device status monitoring
- Easy firmware version deployment interface
- Role-based access control through user groups
- Automated infrastructure deployment using AWS CDK

2024-12-22 13:46 UTC, gibbster commented on amplify/infrastructure/lib/lambda/populate_repo.py
> +        source_repo_url = "https://github.com/folotu/ros2-ota-firmware-updates/archive/refs/heads/main.zip"
Wrong URL

2024-12-22 13:48 UTC, gibbster requested changes
Let's discuss how to handle this. My vote is to use Amplify without explicit CI/CD support (keep it simple and focused on this use case)

2024-12-22 13:48 UTC, gibbster commented on amplify/infrastructure/lib/lambda/populate_repo.py
> +                print('Creating CodeCommit repository...')
New Codecommit repos are no longer supported

2025-11-24 19:33 UTC, Folotu commented on amplify/infrastructure/lib/lambda/populate_repo.py
> +        source_repo_url = "https://github.com/folotu/ros2-ota-firmware-updates/archive/refs/heads/main.zip"
URL has been updated

2026-01-04 00:09 UTC, merged